
services:
  node-app:
    container_name: mynode-app
    ports: 
      - "3000:3000" 
    env_file:
      - ./.env 
    depends_on:
      - mongo 
      - redis
       
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo 

  redis:
    image: redis
 # nginx:
 #   image: nginx:stable-alpine
 #   ports:
  #    - "8080:80"
 #   volumes:
 #     - /Docker/Node-app/nginx/default.conf:/etc/nginx/conf.d/default.conf 
  #  depends_on:
 #    - node-app    

  

volumes:
  mongo-db:
   


       
